from dotenv import load_dotenv
load_dotenv()

from alira.llms import generate_documents, evaluate_documents

texts = ["""Patrimoine vernaculaire valaisan, 40 ans de recherche à l’EPFL / Walliser vernakuläres Baukulturerbe, 40 Jahre Forschung an der EPFL
Présentée dans le cadre du 20e Forum valaisan de la recherche à la Médiathèque Valais – Sion, cette contribution s’inscrit dans une réflexion sur les formes de production et de transmission du savoir liées au patrimoine bâti. La connaissance du patrimoine vernaculaire valaisan s’est construite, depuis plusieurs décennies à l’EPFL, à travers une pratique systématique du relevé architectural, entendue comme instrument de recherche et de projet. Héritière des campagnes pionnières menées autour des collections de Frédéric Aubry, cette tradition a été renouvelée par le Laboratoire des Arts pour les Sciences (LAPIS), qui développe des méthodes de représentation articulant dessin manuel et technologies numériques.""",
"""Ancrées dans le territoire alpin, ces enquêtes associent observation, mesure et restitution graphique pour documenter les typologies constructives, les savoir-faire et les logiques d’implantation du bâti rural. Le relevé devient ainsi un processus actif de production de connaissance, au cœur des enjeux contemporains de sauvegarde, de transformation et de transmission du patrimoine.""",
"""Thiazole Boron Difluoride Dyes with Large Stokes Shift, Solid State Emission and Room-Temperature Phosphorescence
The small Stokes shift and weak emission in the solid state are two main shortcomings associated with the boron-dipyrromethene (BODIPY) family of dyes. This study presents the design, synthesis and luminescent properties of boron difluoro complexes of 2-aryl-5-alkylamino-4-alkylaminocarbonylthiazoles. These dyes display Stokes shifts (Delta lambda, 77-101 nm) with quantum yields (phi(FL)) up to 64.9 and 34.7 % in toluene solution and in solid state, respectively. Some of these compounds exhibit dual fluorescence and room-temperature phosphorescence (RTP) emission properties with modulable phosphorescence quantum yields (phi(PL)) and lifetime (tau(p) up to 251 mu s). The presence of intramolecular H-bonds and negligible pi-pi stacking revealed by X-ray crystal structure might account for the observed large Stokes shift and significant solid-state emission of these fluorophores, while the enhanced spin-orbit coupling (SOC) of iodine and the self-assembly driven by halogen bonding, pi-pi and C-H center dot center dot center dot pi interactions could be responsible for the observed RTP of iodine containing phosphors.""",
"""Characterization of Microwave Substrates for High Accuracy and Long-Term Stability Using Full-Wave Microstrip Ring Resonator Method
An accurate material characterization method for microwave printed-circuit-board substrates is proposed by combining the microwave ring resonator method with iterative full-wave simulations. A detailed error analysis is performed quantitatively to compensate the discrepancy between the estimated value and the actual permittivity. The improved estimation accuracy is a necessity for some highly-precise microwave devices. In addition, the permittivity of FR4 substrate at 109 degrees C operating temperature as a function of time is investigated to validate its long-term stability.""",
"""AllMetal3D: joint prediction of localization, identity and coordination geometry of common metal ions in proteins
Nature uses a variety of metal ions as cofactors for specific tasks. The three main classes of metals in biological systems are alkali ions (e.g. sodium and potassium), alkaline earth ions (e.g. magnesium and calcium) as well as transition metal ions (e.g. zinc or iron and many others). To date no selective predictor to localize each of these metals in a given protein structure exists. Current methods require either preselecting a specific ion (e.g MIB2 ( Lu et al., 2022 ), ESMBind ( Dai et al., 2024 ) or AlphaFold3 ( Abramson et al., 2024 ) or a location (MIC Shub et al. (2024) ). In this work, we describe an extension of the recently introduced Metal3D framework ( Dürr et al., 2023 ) that was originally trained on zinc sites to predict the location of all biologically relevant classes of metal ions as well as to classify their coordination geometry. Our model is the first of its kind and even outperforms Metal3D for the prediction of the location of Zn 2+ and generalizes well to the other metals in terms of location prediction as well as identity classification. Comparing the model to several other available tools such as MetalSiteHunter, AlphaFold3, MIC, MIB2 and MetalHawk highlights important shortcomings in these tools with respect to data bias, prediction of negative sites and selectivity. However, concerning coordination geometry prediction, similar to other work, we find that our method cannot accurately make correct classifications beyond the most common classes in natural proteins i.e. tetrahedral and octahedral arrangements. AllMetal3D is available as ChimeraX extension, standalone web app as well as python package: https://github.com/lcbc-epfl/allmetal3d""",
"""Patrimoine inclusif : lieux et voix invisibilisés
""",
"""Ultra low loss silicon nitride integrated photonics: from chipscale combs, erbium amplifiers to frequency agile low noise lasers
LPQM2""",
"""Optimal design of biomass supply chains with integrated process design
The current work focuses on the optimal design of biomass supply chains, addressing the conversion of raw materials into useful services. The latter include not only heat and power but also synthetic bio-based fuels (e.g. bio-SNG). Optimally pre-designed processing units representing the conversion facilities responsible for the transformation of biomass are employed. This permits the use of standardized units that act as building blocks within a MILP optimization problem, significantly simplifying the formulation and solution of the problem. These building blocks encompass a variety of transformation options and carry specific information regarding their capacity, total processing cost, overall efficiency and energetic performance. Then, the supply chain design optimization problem aims not only to identify the most suitable conversion plant type but also to determine their location by minimizing the overall cost, expressed as the capital and operating expenses of the processing units as well as the transport costs between the points of operation. The above formulation is applied for the conversion of animal manure to different end products in the district of Brig in southern Switzerland. Results reveal the predominance of large centralized bio-SNG producing units as a consequence of their higher conversion efficiency.""",
"""FACETs: Fast and Efficient Compilation for Control–Dataflow Mapping on CGRAs
Reconfigurable computing bridges the gap between the flexibility of general-purpose processors and the efficiency of applicationspecific hardware. Among reconfigurable architectures, Coarse-Grained Reconfigurable Arrays (CGRAs) are particularly promising because they offer high efficiency and low configuration overhead, while maintaining programmability at the operation level. However, mapping high-level applications onto CGRAs remains challenging, as most state-of-the-art approaches either have a limited compilation scope or incur a very high compilation time. To address this challenge, we propose a compilation framework that supports generic control-dataflow graphs by scheduling dataflow graphs under explicit control-flow constraints. The framework adopts a flexible approach that comprises a fast heuristic mapping strategy for non-critical code regions, while enabling aggressive optimizations for performance-critical regions. Experimental results show up to 10× faster compilation for applications with complex control-dataflow graph structures, while achieving comparable or better runtime performance relative to existing approaches.""",
"""Comparison of diffusion MRI and CLARITY fiber orientation estimates in both gray and white matter regions of human and primate brain
Diffusion MRI (dMRI) represents one of the few methods for mapping brain fiber orientations non-invasively. Unfortunately, dMRI fiber mapping is an indirect method that relies on inference from measured diffusion patterns. Comparing dMRI results with other modalities is a way to improve the interpretation of dMRI data and help advance dMRI technologies. Here, we present methods for comparing dMRI fiber orientation estimates with optical imaging of fluorescently labeled neurofilaments and vasculature in 3D human and primate brain tissue cuboids cleared using CLARITY. The recent advancements in tissue clearing provide a new opportunity to histologically map fibers projecting in 3D, which represents a captivating complement to dMRI measurements. In this work, we demonstrate the capability to directly compare dMRI and CLARITY in the same human brain tissue and assess multiple approaches for extracting fiber orientation estimates from CLARITY data. We estimate the three-dimensional neuronal fiber and vasculature orientations from neurofilament and vasculature stained CLARITY images by calculating the tertiary eigenvector of structure tensors. We then extend CLARITY orientation estimates to an orientation distribution function (ODF) formalism by summing multiple sub-voxel structure tensor orientation estimates. In a sample containing part of the human thalamus, there is a mean angular difference of 19 degrees +/- 15 degrees between the primary eigenvectors of the dMRI tensors and the tertiary eigenvectors from the CLARITY neurofilament stain. We also demonstrate evidence that vascular compartments do not affect the dMRI orientation estimates by showing an apparent lack of correspondence (mean angular difference = 49 degrees +/- 23 degrees) between the orientation of the dMRI tensors and the structure tensors in the vasculature stained CLARITY images. In a macaque brain dataset, we examine how the CLARITY feature extraction depends on the chosen feature extraction parameters. By varying the volume of tissue over which the structure tensor estimates are derived, we show that orientation estimates are noisier with more spurious ODF peaks for sub-voxels below 30 mu m(3) and that, for our data, the optimal gray matter sub-voxel size is between 62.5 mu m(3) and 125 mu m(3). The example experiments presented here represent an important advancement towards robust multi-modal MRI-CLARITY comparisons.""",
"""Multi-parametric profiling of plasma-derived extracellular vesicles reveals a disease-associated molecular signature supporting a liquid biopsy approach in myelofibrosis
""",
"""Alpha-NML Universal Predictors
Inspired by the connection between classical regret measures employed in universal prediction and Rényi divergence, we introduce a new class of universal predictors that depend on a real parameter α≥1 . This class interpolates two well-known predictors, the mixture estimators, that include the Laplace and the Krichevsky-Trofimov predictors, and the Normalized Maximum Likelihood (NML) estimator. We point out some advantages of this new class of predictors and study its benefits from two complementary viewpoints: 1) we prove its optimality when the maximal Rényi divergence is considered as a regret measure, which can be interpreted operationally as a middle ground between the standard average and worst-case regret measures; 2) we discuss how it can be employed when NML is not a viable option, as an alternative to other predictors such as Luckiness NML. Finally, we apply the α -NML predictor to the class of discrete memoryless sources (DMS), where we derive simple formulas to compute the predictor and analyze its asymptotic performance in terms of worst-case regret.""",
"""The Feature Speed Formula: a Flexible Approach to Scale Hyper-parameters of Deep Neural Networks
Deep learning succeeds by doing hierarchical feature learning, yet tuning hyper-parameters (HP) such as initialization scales, learning rates etc., only give indirect control over this behavior. In this paper, we introduce a key notion to predict and control feature learning: the angle theta(l) between the feature updates and the backward pass (at layer index l). We show that the magnitude of feature updates after one GD step, at any training time, can be expressed via a simple and general feature speed formula in terms of this angle theta(l), the loss decay, and the magnitude of the backward pass. This angle theta(l) is controlled by the conditioning of the layer-to-layer Jacobians and at random initialization, it is determined by the spectrum of a certain kernel, which coincides with the Neural Tangent Kernel when l = depth. Given theta(l), the feature speed formula provides us with rules to adjust HPs (scales and learning rates) so as to satisfy certain dynamical properties, such as feature learning and loss decay. We investigate the implications of our approach for ReLU MLPs and ResNets in the large width-then-depth limit. Relying on prior work, we show that in ReLU MLPs with iid initialization, the angle degenerates with depth as cos(theta(l)) = Theta(1/root l). In contrast, ResNets with branch scale O(1/root depth) maintain a non-degenerate angle cos(theta(l)) = Theta(1). We use these insights to recover key properties of known HP scalings (such as mu P), and also introduce a new HP scaling for large depth ReLU MLPs with favorable theoretical properties.""",
"""The influence of external electric fields on charge reorganization energy in organic semiconductors
Charge reorganization energies (k) of inter-ring carbon-carbon (IRCC) bond connected conjugated polycyclics are shown to exhibit an electric-field-driven anisotropic character. An external electric field parallel to the IRCC linker(s) reduces k while the field vertical to the molecular plane does the opposite. This anisotropic character can be modulated by introducing inter-ring noncovalent locks into appropriate sites.""",
"""Deep learning assisted image transmission in multimode fibers
We propose a data -driven approach for light transmission control inside multimode fibers (MMFs). Specifically, we show that a convolutional neural network is able to reconstruct amplitude/phase modulated images from scrambled amplitude -only images obtained at the output of a 0.75m long MMF with a fidelity (correlation) as high as 98%. We show that the trained network shows good generalization as well. In particular, it is shown that the network is able to reconstruct images that do not belong to train/test datasets.""",
"""Range Separation of the Interaction Potential in Intermolecular and Intramolecular Symmetry-Adapted Perturbation Theory
Symmetry-adapted perturbation theory (SAPT) is a popular and versatile tool to compute and decompose noncovalent interaction energies between molecules. The intramolecular SAPT (ISAPT) variant provides a similar energy decomposition between two nonbonded fragments of the same molecule, covalently connected by a third fragment. In this work, we explore an alternative approach where the noncovalent interaction is singled out by a range separation of the Coulomb potential. We investigate two common splittings of the 1/r potential into long-range and short-range parts based on the Gaussian and error functions, and approximate either the entire intermolecular/interfragment interaction or only its attractive terms by the long-range contribution. These range separation schemes are tested for a number of intermolecular and intramolecular complexes. We find that the energy corrections from range-separated SAPT or ISAPT are in reasonable agreement with complete SAPT/ISAPT data. This result should be contrasted with the inability of the long-range multipole expansion to describe crucial short-range charge penetration and exchange effects; it shows that the long-range interaction potential does not just recover the asymptotic interaction energy but also provides a useful account of short-range terms. The best consistency is attained for the error-function separation applied to all interaction terms, both attractive and repulsive. This study is the first step toward a fragmentation-free decomposition of intramolecular nonbonded energy.""",
"""Peut-on imaginer un monde sans voiture ?
""",
"""A conditional GABAergic synaptic vesicle marker for Drosophila
Background: Throughout the animal kingdom, GABA is the principal inhibitory neurotransmitter of the nervous system. It is essential for maintaining the homeostatic balance between excitation and inhibition required for the brain to operate normally. Identification of GABAergic neurons and their GABA release sites are thus essential for understanding how the brain regulates the excitability of neurons and the activity of neural circuits responsible for numerous aspects of brain function including information processing, locomotion, learning, memory, and synaptic plasticity, among others. New method: Since the structure and features of GABA synapses are critical to understanding their function within specific neural circuits of interest, here we developed and characterized a conditional marker of GABAergic synaptic vesicles for Drosophila, 9XV5-vGAT. Results: 9XV5-vGAT is validated for conditionality of expression, specificity for localization to synaptic vesicles, specificity for expression in GABAergic neurons, and functionality. Its utility for GABAergic neurotransmitter phenotyping and identification of GABA release sites was verified for ellipsoid body neurons of the central complex. In combination with previously reported conditional SV markers for acetylcholine and glutamate, 9XV5-vGAT was used to demonstrate fast neurotransmitter phenotyping of subesophageal ganglion neurons. Comparison with existing methods: This method is an alternative to single cell transcriptomics for neurotransmitter phenotyping and can be applied to any neurons of interest represented by a binary transcription system driver. Conclusion: A conditional GABAergic synaptic vesicle marker has been developed and validated for GABA neurotransmitter phenotyping and subcellular localization of GABAergic synaptic vesicles.""",
"""Order parameters for antiferromagnetic structures: A first-principles study of iridium manganese
We use density-functional theory to study the ordered states of iridium manganese, demonstrating a simple but powerful method for describing magnetic structures and the transitions among them. As an illustrative example, the coupling of magnetism and crystal structure in IrMn is examined through a rigorous exploration of strain space. We then generate order parameters for the ground-state magnetic structures, providing a comprehensive framework for understanding antiferromagnetic variants and their magnetic anisotropy. In particular, we show how the most direct path between two variant structures can be analytically determined; this technique is used to equate two seemingly contradictory prior studies.""",
"""Increasing the relevance of science for practice and practice for science: Quantitative empirical insights
We present results of a survey conducted with researchers and practitioners involved in a Swiss National Research Programme on steering energy consumption. We analyse what motivates practitioners and researchers to engage in a collaborative research project, their perception of the collaboration intensity (here defined as the frequency of contact) in different project phases, and the extent to which the research project provided useful results for practitioners. Our analyses demonstrate that the intensity of collaboration is a key driver of successful collaboration as it fosters trust between researchers and practitioners. Thereby, it increases the usefulness of the research project for practitioners and their perceived contribution to the success of the research project. Research programmes should thus (1) foster trust through incentivising collaboration between research and practice; (2) facilitate the development of a shared understanding of researchers’ and practitioners’ respective roles; and (3) support the inclusion of practitioners in the project development phase through financial support during the proposal-writing phase.""",
"""Nanocapillary confinement of imidazolium based ionic liquids
Room temperature ionic liquids are salts which are molten at or around room temperature without any added solvent or solution. In bulk they exhibit glass like dependence of conductivity with temperature as well as coupling of structural and transport properties. Interfaces of ionic liquids have been found to induce structural changes with evidence of long range structural ordering on solid-liquid interfaces spanning length scales of 10-100 nm. Our aim is to characterize the influence of confinement on the structural properties of ionic liquids. We present the first conductivity measurements on ionic liquids of the imidazolium type in single conical glass nanopores with confinements as low as tens of nanometers. We probe glassy dynamics of ionic liquids in a large range of temperatures (-20 to 70 degrees C) and nanopore opening sizes (20-600 nm) in silica glass nanocapillaries. Our results indicate no long range freezing effects due to confinement in nanopores with diameters as low as 20 nm. The studied ionic liquids are found to behave as glass like liquids across the whole accessible confinement size and temperature range.""",
"""CrossFeat: Semantic Cross-modal Attention for Pedestrian Behavior Forecasting
Forecasting pedestrian behaviors is essential for autonomous vehicles to ensure safety in urban scenarios. Previous works addressed this problem based on motion alone, omitting several additional behavioral cues helping understanding pedestrians’ true intentions. We address the problem of forecasting pedestrian actions through joint reasoning about pedestrians’ past behaviors and their surrounding environments. For this, we propose a Transformer-based feature fusion approach, where multi-modal inputs about pedestrians and environments are all mapped into a common space, then jointly processed through self and cross-attention mechanisms to take context into account. We also use a semantic segmentation map of the current input frame, rather than the full temporal visual stream, to further focus on semantic reasoning. We experimentally validate and analyze our approach on two benchmarks about pedestrian crossing and Stop&Go motion changes, which rely on several standard self-driving datasets centered around interactions with pedestrians (JAAD, PIE, TITAN), and show that our semantic joint reasoning yields state-of-the-art results.""",
"""Role of ice cover on the diversity and composition of bacteria communities in warming arctic lakes
Arctic lakes are among the most extreme and least explored freshwater environments, where seasonal ice cover creates unique ecological niches that sustain abundant microbial communities. These microbes are central to nutrient cycling, yet their responses to rapid, climate-driven shifts in ice phenology remain poorly understood. In this study, we examined how lake ice cover structures microbial community composition and function, with a particular focus on nitrogen cycling. Fieldwork was conducted at two lakes in West Greenland during June 2025, when ice cover was still present but undergoing melt. We integrated in situ environmental monitoring, chemical profiling, and 16s rRNA sequencing with physiological and functional assays to characterize microbial assemblages across ice, water column, and bioaerosol compartments. Preliminary findings reveal that ice harbors distinct and metabolically active bacterial communities with elevated nitrogen and ammonia concentrations compared to the underlying water column, suggesting that ice-associated microbiomes may play an overlooked role in Arctic lake biogeochemistry. These results provide new insights into how ice cover""",
"""sustains specialized microbial communities, their contribution to nitrogen transformations, and how ongoing changes in Arctic ice regimes may reshape ecosystem functioning under climate change.""",
"""Coordination-Driven Monolayer-to-Bilayer Transition in Two-Dimensional Metal–Organic Networks
We report on monolayer-to-bilayer transitions in 2D metal–organic networks (MONs) from amphiphiles supported at the water–air interface. Functionalized calix[4]arenes are assembled through the coordination of selected transition metal ions to yield monomolecular 2D crystalline layers. In the presence of Ni(II) ions, interfacial self-assembly and coordination yields stable monolayers. Cu(II) promotes 2D coordination of a monolayer which is then diffusively reorganizing, nucleates, and grows a progressive amount of second layer islands. Atomic force microscopic data of these layers after transfer onto solid substrates reveal crystalline packing geometries with submolecular resolution as they are varying in function of the building blocks and the kinetics of the assembly. We assign this monolayer-to-bilayer transition to a diffusive reorganization of the initial monolayers owing to chemical vacancies of the predominant coordination motif formed by Cu2+ ions. Our results introduce a new dimension into the controlled monolayer-to-multilayer architecturing of 2D metal–organic networks.""",
"""Hydrodynamics In A Condensation Regime: The Disordered Asymmetric Zero-Range Process
We study asymmetric zero-range processes on Z with nearest-neighbour jumps and site disorder. The jump rate of particles is an arbitrary but bounded nondecreasing function of the number of particles. For any given environment satisfying suitable averaging properties, we establish a hydrodynamic limit given by a scalar conservation law including the domain above critical density, where the flux is shown to be constant.""",
"""Optimizing neighborhood-scale walkability
Many designers and researchers have grappled with the problem of optimally locating buildings and use types in a neighborhood-scale development. But little work has used data-driven optimization to aid in creating urban design schemes. The paradigm of single-use Euclidian zoning has heavily impacted the way our neighborhoods, cities, and suburbs are designed, resulting in the physical separation of uses. However, as we grapple with emerging issues of environmental and social sustainability in cities, there is a pressing need to consider alternative urban designs that require less dependence on personal automobiles and that foster healthier cities. In this paper, we develop a methodology for (1) automatically assessing the walkability of neighborhoods by adopting a common walkability metric and (2) optimizing the layout of buildings and amenities across a known grid in order to maximize the walkability metric. We apply this methodology to a case study of the Potrero Hill neighborhood in San Francisco, California. We find that, in comparison to the existing layout that can be characterized by Euclidian-style separation of uses, the optimized layout suggests distributing amenities across the street network, resulting in a two-fold increase in walkability. This tool and analysis have the potential to provide computational and data-driven support for urban designers and researchers hoping to understand and improve the walkability of urban spaces.""",
"""Verifying quantum computations at scale: A cryptographic leash on quantum devices
Rapid technological advances point to a near future where engineered devices based on the laws of quantum mechanics are able to implement computations that can no longer be emulated on a classical computer. Once that stage is reached, will it be possible to verify the results of the quantum device? Recently, Mahadev introduced a solution to the following problem: Is it possible to delegate a quantum computation to a quantum device in a way that the final outcome of the computation can be verified on a classical computer, given that the device may be faulty or adversarial and given only the ability to generate classical instructions and obtain classical readout information in return? Mahadev's solution combines the framework of interactive proof systems from complexity theory with an ingenious use of classical cryptographic techniques to tie a "cryptographic leash" around the quantum device. In these notes I give a self-contained introduction to her elegant solution, explaining the required concepts from complexity, quantum computing, and cryptography, and how they are brought together in Mahadev's protocol for classical verification of quantum computations.""",
"""Abstract IA02: Cancer-specific foundation models: Friend or foe in healthcare AI?
Foundation models have become a powerful tool in single-cell transcriptomics, enabling broad generalization across tasks such as cell type annotation, data integration, and drug response prediction. Yet, most current models are trained predominantly on healthy cells, with a strong bias toward peripheral blood mononuclear cells. This raises an important question: how well do these models generalize to cancer-specific contexts? In this talk, I will explore whether training a foundation model exclusively on malignant cells—across diverse cancer types—can improve performance on tasks relevant to cancer biology and treatment. I will introduce CancerFoundation, a single-cell foundation model trained on malignant cells from over 40 tumor types. The model incorporates strategies for addressing tissue imbalance and technical variation, including domain-invariant training and tailored sampling. Through this work, I aim to address whether disease-specific pretraining can better capture the molecular features of cancer and improve the utility of foundation models in oncology applications such as batch integration and drug response prediction. Citation Format: Alexander Theus, Florian Barkmann, David Wissel, Tobias Scheithauer, Maria Brbic, Valentina Boeva. Cancer-specific foundation models: Friend or foe in healthcare AI? [abstract]. In: Proceedings of the AACR Special Conference in Cancer Research: Artificial Intelligence and Machine Learning; 2025 Jul 10-12; Montreal, QC, Canada. Philadelphia (PA): AACR; Clin Cancer Res 2025;31(13_Suppl):Abstract nr IA02.""",
"""Randomisering under en pandemi
23.06.2020: Medisin og tall - Randomisering er en bærebjelke i evidensbasert medisin.""",
"""Design and Validation of a Tripping-Eliciting Platform Based on Compliant Random Obstacles
Goal: The experimental study of the stumble phenomena is essential to develop novel technological solutions to limit harmful effects in at-risk populations. A versatile platform to deliver realistic and unanticipated tripping perturbations, controllable in their strength and timing, would be beneficial for this field of study. Methods: We built a modular tripping-eliciting system based on multiple compliant trip blocks that deliver unanticipated tripping perturbations. The system was validated with a study with 9 healthy subjects. Results: The system delivered 33 out of 34 perturbations (a minimum of 3 per subject) during the desired gait phase, and 31 effectively induced a tripping event. The recovery strategies adopted after the perturbations were qualitatively consistent with the literature. The analysis of the inertial motion unit signals and the questionnaires suggests a limited adaptation to the perturbation throughout experiments. Conclusions: The platform succeeded in providing realistic trip perturbations, concurrently limiting subjects' adaptation. The presence of multiple compliant obstacles, tunable regarding position and perturbation strength, represents a novelty in the field, allowing the study of stumbling phenomena caused by obstacles with different levels of sturdiness. The overall system is modular and can be easily adapted for different applications.""",
"""Flexible Medium Voltage DC Source Utilizing Series Connected Modular Multilevel Converters
This paper presents the converter configuration acting as a medium voltage DC source. In order to obtain desired voltage across the DC terminals, two series connected modular multilevel converters are used. The use of modular multilevel converters results in high degrees of modularity, flexibility, reliability, current limiting capability during DC faults, as well as the outstanding operational performances. Each modular multilevel converter is connected to the 3.3 kV AC supply, while ensuring arbitrary voltage in the range of +/- 5 kV across its DC terminals. Consequently, series connection of two power units allows for +/- 10 kV to be synthesized across the converter's DC terminals. Moreover, there is a freedom of choice with regards to the way that two modular multilevel converters share the output DC voltage reference. Therefore, studies focusing on converter dynamics and efficiency for various voltage sharing profiles are conducted. As a result, the most optimal voltage sharing profile is generated, covering the whole operating range of the converter.""",
"""Effect of likelihood misspecification in Gaussian process-driven autonomous experimentation
In recent years, several groups have designed Autonomous Experiment (AE) models with the aim of using them as an alternative method for neutron scattering scanning. In an AE, Gaussian processes (GPs) are most frequently used due to their interpretability, their non-parametric nature, their universal approximation, and their closed-form predictive distribution. GPs have two key components, namely, the model for the likelihood of a neutron count knowing the underlying dynamic structure factor and the acquisition function. In this paper, we investigate the impact, on the quality of an AE, of the likelihood and acquisition function choices, in energy scans and (Q, ω) ones, with respect to the signal-over-noise ratio. While we hypothesized that the quality of GP predictions would decrease when the normal to Poisson likelihood approximation breaks down at low count rates, we found that the use of the correct Poisson likelihood does not improve the quality of the data collected, as well as yields very poor results in (Q, ω) scans at low count rates. In fact, the best results are obtained with a combination of normal likelihood, including the observation noise, and the change in variance acquisition function. In addition, we find that the performance, or quality of the predictive distribution, is a misleading measure of efficiency, that is, of the quality of the data collected.""",
"""Automated identification of local contamination in an Arctic aerosol time series
A common challenge of Atmospheric measurements in remote environments is to identify local pollution from nearby sources. During the MOSAiC (Multidisciplinary drifting Observatory for the Study of Arctic Climate) expedition, we measured aerosol and gaseous atmospheric composition on the bow of the research vessel Polarstern in the Arctic Ocean. Our measurements were occasionally impacted by pollution from the ship exhaust, or by ongoing activities on sea-ice such as passing skidoos or use of generators. We developed an automated method to identify such pollution events. Here, we present the algorithm used to clean the aerosol dataset collected during the MOSAiC expedition.""",
"""Training in a novel immersive catheter ablation simulator using 3D MR heart models of individual patients improves performance of future electrophysiologists
""",
"""Follicular regulatory helper T cells control the response of regulatory B cells to a high-cholesterol diet
Aims B cell functions in the process of atherogenesis have been investigated but several aspects remain to be clarified.""",
"""Human self and Neurosurgery: Advances and insights from Geneva
Introduction: The preservation of the human self—a fundamental yet underexplored aspect of neurosurgical practice—has gained increasing attention in recent years. Research question: How can neural correlates of self-consciousness be identified, monitored, and protected during brain tumor surgery, and how might this reshape the concept of “onco-functional balance”? Material and methods: This review synthesizes emerging evidence from neuroimaging, neuropsychology, and intraoperative neurophysiology to build a framework for integrating the concept of self into modern neurosurgical practice. Results: We describe the anatomical and functional basis of bodily and cognitive self-awareness, highlighting the roles of interoception, multisensory integration, and higher-order cortical networks such as the medial prefrontal cortex, insula and temporoparietal junction. We outline perioperative tools for clinical assessment, including validated scales for anosognosia and disownership, as well as the Self-Other Voice Discrimination (SOVD) paradigm and Heartbeat-Evoked Potentials (HEPs), which offer quantifiable markers of self-processing. Discussion and conclusion: We argue for a reconceptualization of “eloquent” cortex to include regions critical for the preservation of self. As neurosurgery advances toward precision-guided, patient-centered care, protecting the self must become an explicit goal alongside motor, sensory, and language preservation. Future directions include real-time intraoperative monitoring of HEPs, development of functional risk maps for self-related structures, and broader implementation of personalized, neurocognitive surgical planning. Ultimately, this work proposes a shift from an “onco-functional” to an “onco-functional-identity” paradigm—where the integrity of the patient's personality, agency, and awareness becomes a measurable, preservable endpoint of neurosurgical care.""",
"""Search for Physics beyond the Standard Model in Events with Overlapping Photons and Jets
Results are reported from a search for new particles that decay into a photon and two gluons, in events with jets. Novel jet substructure techniques are developed that allow photons to be identified in an environment densely populated with hadrons. The analyzed proton-proton collision data were collected by the CMS experiment at the LHC, in 2016 at √s=13  TeV, and correspond to an integrated luminosity of 35.9  fb−1. The spectra of total transverse hadronic energy of candidate events are examined for deviations from the standard model predictions. No statistically significant excess is observed over the expected background. The first cross section limits on new physics processes resulting in such events are set. The results are interpreted as upper limits on the rate of gluino pair production, utilizing a simplified stealth supersymmetry model. The excluded gluino masses extend up to 1.7 TeV, for a neutralino mass of 200 GeV and exceed previous mass constraints set by analyses targeting events with isolated photons.""",
"""The E3-ome gene-centric compendium reveals the human E3 ligase landscape
To define and systematically characterize the human E3 ubiquitin ligase (E3) landscape, we generated the E3-ome, a compendium of E3s encoded by the human genome. The E3-ome integrates experimental data, bioinformatics, and published research, revealing 672 high-confidence E3s. We standardized E3 classifications to create a unified framework for annotation and comparative analysis. The E3-ome identified several previously unrecognized domains, motifs, E3 candidates, and relationships, expanding the diversity of E3s. Furthermore, the E3-ome mapped the spatial and physiological organization of E3s across human tissues and cell types, revealing context-dependent E3s. Genetic analyses identified disease-associated variants across the E3-ome, linking E3s to diverse human pathologies. Together, these analyses define the human E3 landscape at high resolution and deliver a foundational resource to drive mechanistic and therapeutic discovery.""",
"""Regularity Matters: Designing Practical FPGA Switch-Blocks
Several techniques have been proposed for automatically searching for FPGA switch-blocks which typically show some tangible advantage over the well-known academic architectures. However, the resulting switch-blocks usually exhibit high levels of irregularity, in contrast with what can be observed in a typical commercial architecture. One wonders whether the architectures produced by such search methods can actually be laid out in an efficient manner while retaining the perceived gains. In this work, we propose a new switch-block exploration method that enhances a recently published search algorithm by combining it with ILP, in order to guarantee that the obtained solution satisfies arbitrary regularity constraints. We measure the impact of regularity constraints commonly seen in industrial architectures (such as limiting the number of different multiplexer sizes or forced sharing of inputs between pairs of multiplexers) and observe benefits to the routability of complex circuits with only a limited reduction in performance.""",
"""Non-canonical resource allocation in heterotrophically growing Thermoanaerobacter kivui
Allocation of resources in the costly proteome reflects trade-offs between cellular functions. For example, proteome composition of Escherichia coli is significantly regulated by growth rate. An increasing anabolic, especially ribosomal, proteome fraction correlates with a decreasing catabolic proteome fraction at faster growth, which then leads to changes in catabolism. Our systems-level studies of the thermophilic acetogen Thermoanaerobacter kivui when growth rate is varied over two orders of magnitude revealed a different strategy: proteome allocation is only partially controlled by growth rate, and metabolic rates are primarily controlled posttranslationally. At slower growth, ribosome numbers are controlled by rRNA concentrations with an excess of ribosomal proteins. Composition of the catabolic proteome is uncoupled from catabolic rates as indicated by flux analysis. This study adds to the understanding of acetogenic Clostridia, which are of interest for biotechnological processes in a carbon-neutral economy, and points to a complex landscape of microbial ecophysiological strategies.""",
"""Lecture Notes on Intermittent Weak Solutions of the Three-dimensional Navier-Stokes Equations
This summary closely follows the paper Buckmaster et al. (Wild solutions of the Navier-Stokes equations whose singular sets in time have hausdorff dimension strictly less than 1, 2018. ArXiv:1809.00600) by the authors, which contains all the details regarding the specific gluing and convex integration technique used here. The lectures will be supplemented with material from the recent review paper Buckmaster and Vicol (EMS Surv. Math. Sci. 6(1/2):173–263, 2019), which contains the necessary background concerning weak solutions of the Euler and Navier-Stokes equations, their connection to phenomenological theories of fully developed turbulence, and the convex integration methods used to construct them.""",
"""Large (Vision) Language Models are Unsupervised In-Context Learners
Recent advances in large language and vision-language models have enabled zero-shot inference, allowing models to solve new tasks without task-specific training. Various adaptation techniques such as prompt engineering, In-Context Learning (ICL), and supervised fine-tuning can further enhance the model’s performance on a downstream task, but they require substantial manual effort to construct effective prompts or labeled examples. In this work, we introduce a joint inference framework for fully unsupervised adaptation, eliminating the need for manual prompt engineering and labeled examples. Unlike zero-shot inference, which makes independent predictions, the joint inference makes predictions simultaneously for all inputs in a given task. Since direct joint inference involves computationally expensive optimization, we develop efficient approximation techniques, leading to two unsupervised adaptation methods: unsupervised fine-tuning and unsupervised ICL. We demonstrate the effectiveness of our methods across diverse tasks and models, including language-only Llama-3.1 on natural language processing tasks, reasoning-oriented Qwen2.5-Math on grade school math problems, vision-language OpenFlamingo on vision tasks, and the API-only access GPT-4o model on massive multi-discipline tasks. Our experiments demonstrate substantial improvements over the standard zero-shot approach, including 39% absolute improvement on the challenging GSM8K math reasoning dataset. Remarkably, despite being fully unsupervised, our framework often performs on par with supervised approaches that rely on ground truth labels.""",
"""Coral genetic structure in the Western Indian Ocean mirrors ocean circulation and thermal stress
Global warming and rising sea temperatures are pushing many reef-building coral species towards extinction. As thermal tolerance in corals is partially heritable, identifying genes under thermal selection is critical for targeted biodiversity management. However, it remains unclear how large breaks in connectivity (>100 km of open sea) affect the spread of adaptive alleles for different coral species in discontinuous reef networks such as the West Indian Ocean (WIO). To address this, we applied a seascape genomics approach to model (i) population connectivity and (ii) thermal adaptive potentials for two keystone coral species, Acropora muricata and Pocillopora damicornis , across the WIO. For both species, corals from the Seychelles were predominantly genetically isolated from corals in Rodrigues and Mauritius, putatively an effect of regional oceanographic barriers. Furthermore, sea currents during reproductive periods better predicted genetic connectivity than did Euclidean distances for both species, highlighting that connectivity models can serve as proxies to understand dispersal potential depending on reproductive strategies. Spatial patterns of neutral genetic variation were best explained by sea surface temperature variability and mean degree heating weeks. When used in genotype-environment association (GEA) analyses, we identified hundreds of loci under putative thermal selection from linked to known heat stress responses. In A. muricata , five Sacsin genes-co-chaperones of the Hsp70 heat-shock protein involved in thermal stress response-were identified, alongside genes related to immune defence, antioxidant response, signalling, and protein folding. In contrast, only the centromere protein V, involved in mitosis, was enriched in P. damicornis. By integrating patterns of gene flow with molecular adaptations to estimate species-specific adaptive potentials, we found that large sea distances and strong oceanographic barriers inhibit the genetic exchange of adapted genotypes across the WIO, providing valuable insights to guide local and regional biodiversity management in this region.""",
"""Designing cities in a changing world. Opening words
The Seminar is addressed to doctoral students in the fields of Architecture, Urbanism, Global Health & Humanities and Social Sciences, interested in the use of the One Health concept (OH) as a tool to tackle urban themes (the city, the territory and the ways in which we inhabit them). Scientific training in OH methods requires innovation, in order to take into account, on the one hand, the rapid evolution of the socio-spatial realities under study, and on the other, the variety of languages, techniques, and scales involved in the description and analysis.""",
"""Sequential Bone-Marrow Cell Delivery of VEGFA/S1P Improves Vascularization and Limits Adverse Cardiac Remodeling After Myocardial Infarction in Mice
Microvascular dysfunction and resulting tissue hypoxia is a major contributor to the pathogenesis and evolution of cardiovascular diseases (CVD). Diverse gene and cell therapies have been proposed to preserve the microvasculature or boost angiogenesis in CVD, with moderate benefit. This study tested in vivo the impact of sequential delivery by bone-marrow (BM) cells of the pro-angiogenic factors vascular endothelial growth factor (VEGFA) and sphingosine-1-phosphate (S1P) in a myocardial infarction model. For that, mouse BM cells were transduced with lentiviral vectors coding for VEGFA or sphingosine kinase (SPHK1), which catalyzes S1P production, and injected them intravenously 4 and 7 days after cardiac ischemia-reperfusion in mice. Sequential delivery by transduced BM cells of VEGFA and S1P led to increased endothelial cell numbers and shorter extravascular distances in the infarct zone, which support better oxygen diffusion 28 days post myocardial infarction, as shown by automated 3D image analysis of the microvasculature. Milder effects were observed in the remote zone, together with increased proportion of capillaries. BM cells delivering VEGFA and S1P also decreased myofibroblast abundance and restricted adverse cardiac remodeling without major impact on cardiac contractility. The results indicate that BM cells engineered to deliver VEGFA/S1P angiogenic factors sequentially may constitute a promising strategy to improve micro-vascularization and oxygen diffusion, thus limiting the adverse consequences of cardiac ischemia.""",
"""Quantum Spin Dynamics Due to Strong Kitaev Interactions in the Triangular-Lattice Antiferromagnet CsCeSe<sub>2 </sub>
The extraordinary properties of the Kitaev model have motivated an intense search for new physics in materials that combine geometrical and bond frustration. In this Letter, we employ inelastic neutron scattering, spin wave theory, and exact diagonalization to study the spin dynamics in the perfect triangularlattice antiferromagnet (TLAF) CsCeSe2. This material orders into a stripe phase, which is demonstrated to arise as a consequence of the off-diagonal bond-dependent terms in the spin Hamiltonian. By studying the spin dynamics at intermediate fields, we identify an interaction between the single-magnon state and the two-magnon continuum that causes decay of coherent magnon excitations, level repulsion, and transfer of spectral weight to the continuum that are controlled by the strength of the magnetic field. Our results provide a microscopic mechanism for the stabilization of the stripe phase in TLAF and show how complex many-body physics can be present in the spin dynamics in a magnet with strong Kitaev coupling even in an ordered ground state.""",
"""Optimized antiangiogenic reprogramming of the tumor microenvironment potentiates CD40 immunotherapy
Cancer immunotherapies are increasingly combined with targeted therapies to improve therapeutic outcomes. We show that combination of agonistic anti-CD40 with antiangiogenic antibodies targeting 2 proangiogenic factors, vascular endothelial growth factor A (VEGFA) and angiopoietin 2 (Ang2/ANGPT2), induces pleiotropic immune mechanisms that facilitate tumor rejection in several tumor models. On the one hand, VEGFA/Ang2 blockade induced regression of the tumor microvasculature while decreasing the proportion of nonperfused vessels and reducing leakiness of the remaining vessels. On the other hand, both anti-VEGFA/Ang2 and anti-CD40 independently promoted proinflammatory macrophage skewing and increased dendritic cell activation in the tumor microenvironment, which were further amplified upon combination of the 2 treatments. Finally, combined therapy provoked brisk infiltration and intratumoral redistribution of cytotoxic CD8+ T cells in the tumors, which was mainly driven by Ang2 blockade. Overall, these nonredundant synergistic mechanisms endowed T cells with improved effector functions that were conducive to more efficient tumor control, underscoring the therapeutic potential of antiangiogenic immunotherapy in cancer.""",
"""Supervised Pretraining and Self-Supervised Finetuning enables Robust Reconstruction of High-Resolution 7T MP2RAGE for Multiple Sclerosis
Motivation: The infeasibility to collect large datasets of high-resolution, fully-sampled 7T data hinders the training of deep learning reconstructions for accelerated high-resolution 7T scans. Goal(s): Demonstrate that combining pretraining on fully-sampled scans from 1.5/3T and self-supervised finetuning on a few undersampled 7T scans enables robust reconstruction. Approach: High-resolution(0.5mm isotropic), 3D, 7T MP2RAGE scans of multiple sclerosis patients are used for finetuning/testing. Results: Deep learning reconstructions from one 7T scan have higher apparent SNR than a median of GRAPPA reconstructions from three scans, currently used for assessment, with similar tissue contrast and lesion conspicuity, potentially reducing scan time by a factor of three. Impact: Very high-resolution 3D scans can require infeasible acquisition time to generate images suitable for clinical use. Our work shows the potential for deep learning reconstructions to reduce scan time by a factor of three, without fully-sampled 7T data.""",
"""W+W− boson pair production in proton-proton collisions at √s=13  TeV
A measurement of the W+W− boson pair production cross section in proton-proton collisions at √s=13  TeV is presented. The data used in this study are collected with the CMS detector at the CERN LHC and correspond to an integrated luminosity of 35.9  fb−1. The W+W− candidate events are selected by requiring two oppositely charged leptons (electrons or muons). Two methods for reducing background contributions are employed. In the first one, a sequence of requirements on kinematic quantities is applied allowing a measurement of the total production cross section, 117.6±6.8  pb, which agrees well with the theoretical prediction. Fiducial cross sections are also reported for events with zero or one jet, and the change in the zero-jet fiducial cross section with the jet transverse momentum threshold is measured. Normalized differential cross sections are reported within the fiducial region. A second method for suppressing background contributions employs two random forest classifiers. The analysis based on this method includes a measurement of the total production cross section and also a measurement of the normalized jet multiplicity distribution in W+W− events. Finally, a dilepton invariant mass distribution is used to probe for physics beyond the standard model in the context of an effective field theory, and constraints on the presence of dimension-6 operators are derived.""",
"""Unsupervised landmark analysis for jump detection in molecular dynamics simulations
Molecular dynamics is a versatile and powerful method to study diffusion in solid-state ionic conductors, requiring minimal prior knowledge of equilibrium or transition states of the system's free energy surface. However, the analysis of trajectories for relevant but rare events, such as a jump of the diffusing mobile ion, is still rather cumbersome, requiring prior knowledge of the diffusive process in order to get meaningful results. In this work, we present a novel approach to detect the relevant events in a diffusive system without assuming prior information regarding the underlying process. We start from a projection of the atomic coordinates into a landmark basis to identify the dominant features in a mobile ion's environment. Subsequent clustering in landmark space enables a discretization of any trajectory into a sequence of distinct states. As a final step, the use of the smooth overlap of atomic positions descriptor allows distinguishing between different environments in a straightforward way. We apply this algorithm to ten Li-ionic systems and perform in-depth analyses of cubic Li7La3Zr2O12, tetragonal Li10GeP2S12, and the beta-eucryptite LiAlSiO4. We compare our results to existing methods, underscoring strong points, weaknesses, and insights into the diffusive behavior of the ionic conduction in the materials investigated.""",
"""A normative cortical T1 atlas for single-subject pathology detection at 7T
Quantitative MRI allows establishing normative atlases of relaxometry parameters which enable single-subject comparisons for anomaly detection. The large anatomical inter-subject variability of the brain cortex and its convoluted shape, however, complicate such comparison in this region. In this study, a method to align inter-subject brain cortices is proposed and a voxel-wise normative T1 atlas in the cortex is built from a cohort of 133 healthy subjects scanned at 7T. The atlas is used to detect and characterize T1 alterations in two multiple sclerosis patients on a single-subject basis."""]

generated_texts = generate_documents(query="perovskite solar cells", n=3, examples=texts[24:29])
print(generated_texts)

evaluations = evaluate_documents(query="perovskite solar cells", texts=generated_texts)
print(evaluations)
